name: janet
adopt-info: janet
summary: functional and imperative programming language and bytecode interpreter
description: |
    **Janet** is a functional and imperative programming language and bytecode interpreter. It is a
    modern lisp, but lists are replaced
    by other data structures (arrays, tables (hash table), struct (immutable hash table), tuples).
    The language also supports bridging to native code written in C, meta-programming with macros, and bytecode assembly.
base: core18
confinement: classic
grade: stable
apps:
    janet:
        command: usr/bin/janet
        adapter: none
    jpm:
        command: usr/bin/jpm
        adapter: none
parts:
    janet:
        plugin: make
        source: .
        make-parameters: [PREFIX=/usr]
        build-packages: [build-essential]
        override-build: |
            snapcraftctl build
            snapcraftctl set-version "$($SNAPCRAFT_PART_INSTALL/usr/bin/janet -e '(print "Version: " janet/version)' | awk '{ print $2 }')"
